Change kubernetes version
uncomment and change version 

ERROR: Cannot install -r /tmp/src/requirements.txt (line 10) and kubernetes==9.0.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested kubernetes==9.0.1
    openshift 0.10.0 depends on kubernetes~=10.0

doesnt make sense since its already commented out in requirements.txt, but still installing the specific kubernetes==9.0.1 version